// Renders the schedules page (src/ui/page.ts) with sample data into HTML for the documentation
// site, so its illustration is the program's real output. Run: node scripts/site-demos.mjs
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { DEFAULT_SETTINGS, saveSettings } from "../src/core/settings.js";
import { ScheduleStore } from "../src/core/store.js";
import { ThreadStore } from "../src/core/threads.js";
import { setClock } from "../src/core/time.js";
import { SchedulesPage } from "../src/ui/page.js";

const PALETTE: Record<string, string> = {
  "30": "#1b1e24",
  "31": "#d07277",
  "32": "#a1c181",
  "33": "#dec184",
  "34": "#74ade8",
  "35": "#c678dd",
  "36": "#6eb4bf",
  "37": "#dce0e5",
  "90": "#8b93a1",
  "91": "#d07277",
  "92": "#a1c181",
  "93": "#f4a949",
  "94": "#74ade8",
  "95": "#c678dd",
  "96": "#6eb4bf",
  "97": "#ffffff",
};
const SGR = new RegExp(`${String.fromCharCode(27)}\\[([0-9;]*)m`, "g");
const escapeHtml = (t: string) =>
  t.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

/** One terminal line with SGR codes, as HTML spans. */
export function ansiToHtml(line: string): string {
  let out = "";
  let last = 0;
  let st: {
    b?: boolean;
    d?: boolean;
    r?: boolean;
    u?: boolean;
    fg?: string | undefined;
    bg?: string | undefined;
  } = {};
  const flush = (text: string) => {
    if (!text) return;
    let { fg, bg } = st;
    if (st.r) [fg, bg] = [bg ?? "#1b1e24", fg ?? "#dce0e5"];
    const css = [
      fg && `color:${fg}`,
      bg && `background:${bg}`,
      st.b && "font-weight:600",
      st.d && "opacity:.62",
      st.u && "text-decoration:underline",
    ].filter(Boolean);
    out += css.length
      ? `<span style="${css.join(";")}">${escapeHtml(text)}</span>`
      : escapeHtml(text);
  };
  for (const m of line.matchAll(SGR)) {
    flush(line.slice(last, m.index));
    last = (m.index ?? 0) + m[0].length;
    const codes = (m[1] || "0").split(";");
    for (let i = 0; i < codes.length; i++) {
      const c = codes[i] ?? "";
      if (c === "0") st = {};
      else if (c === "1") st.b = true;
      else if (c === "2") st.d = true;
      else if (c === "4") st.u = true;
      else if (c === "7") st.r = true;
      else if (c === "22") st.b = st.d = false;
      else if (c === "24") st.u = false;
      else if (c === "27") st.r = false;
      else if (c === "39") st.fg = undefined;
      else if (c === "49") st.bg = undefined;
      else if ((c === "38" || c === "48") && codes[i + 1] === "2") {
        const rgb = `rgb(${codes[i + 2]},${codes[i + 3]},${codes[i + 4]})`;
        if (c === "38") st.fg = rgb;
        else st.bg = rgb;
        i += 4;
      } else if (PALETTE[c]) st.fg = PALETTE[c];
      else if (/^(4[0-7]|10[0-7])$/.test(c)) st.bg = PALETTE[String(Number(c) - 10)];
    }
  }
  flush(line.slice(last));
  return out;
}

const T0 = new Date(2026, 9, 5, 14, 12).getTime(); // a Monday afternoon
const at = (d: number, h: number, m = 0) => new Date(2026, 9, d, h, m).getTime();
const dir = mkdtempSync(join(tmpdir(), "rewake-site-"));
try {
  saveSettings(dir, { ...DEFAULT_SETTINGS, clock: "12h" });
  setClock("12h");
  const threads = new ThreadStore(dir);
  const store = new ScheduleStore(dir);
  threads.update(
    "s-1",
    "/work/agent-rewake",
    { title: "Split the scheduler", agentName: "Claude Agent", autoResume: true },
    T0,
  );
  threads.update("s-2", "/work/api", { title: "Fix flaky CI", agentName: "Codex" }, T0);
  threads.update(
    "s-3",
    "/work/agent-rewake",
    { title: "Release notes", agentName: "Claude Agent" },
    T0,
  );
  store.create({
    sessionId: "s-1",
    cwd: "/work/agent-rewake",
    text: "Resume the work from where you were interrupted. Agent Rewake sent this message after a usage limit reset.",
    dueAt: at(5, 17, 1),
    kind: "limit_resume",
    createdBy: "form",
    now: T0,
    followUps: ["Then run the tests and open a PR"],
  });
  store.create({
    sessionId: "s-2",
    cwd: "/work/api",
    text: "Check whether the CI run passed and fix any failures",
    dueAt: T0 + 30 * 60_000,
    createdBy: "agent",
    now: T0,
  });
  store.create({
    sessionId: "s-3",
    cwd: "/work/agent-rewake",
    text: "Summarise yesterday's merged PRs for the changelog",
    dueAt: at(6, 9),
    createdBy: "form",
    now: T0,
    repeat: { cron: "0 9 * * 1-5" },
  });
  const page = new SchedulesPage({ stateDir: dir, now: () => T0, locale: "en-US" });
  const frame = page.render(100, 15);
  writeFileSync(
    join(process.env.REWAKE_SITE_GENERATED ?? "site/src/generated", "schedules-page.html"),
    `<!-- Generated by scripts/site-demos.mjs from src/ui/page.ts (100×15, sample data). Don't edit. -->\n${frame.lines.map(ansiToHtml).join("\n")}\n`,
  );
  console.log("wrote site/src/generated/schedules-page.html");
} finally {
  rmSync(dir, { recursive: true, force: true });
}
